### ISSUE TITLE
cached broadcast routes are reset when performing routes.calculate()

### ISSUE THREAD

**Issue by murali-reddy** [weaveworks/mesh#112]
While performing mesh scaling tests on cluster sizes > 175 nodes even with combined patch #110, #110 (whose intent is to rate limit number of [`peer.routes()`](https://github.com/weaveworks/mesh/blob/v0.2/routes.go#L193) calls performed) it is still observed high number (at the order 200-300 calls per second) of `calculateBroadcast()` which calls `peer.routes()`. peer.routes() is of O(n^2) complexity

`routes.lookupOrCalculate` optimizes number of routes() calls made by caching the results in routes.broadcast and routes.broadcastAll. However routes.calculate() reset's cached data every time its called resulting lookupOrCalculate to miss the cache and perform routes calculation.

https://github.com/weaveworks/mesh/blob/v0.2/routes.go#L210-L211

**Comment by bboreham** [comment]
Isn't this intentional?  We call `calculate` when something changes like a connection added or deleted, so we want to discard any calculations based on the old info.

Most of those changes are uninteresting for most broadcast routes, but figuring out which are interesting is the hard part.

**Comment by murali-reddy** [comment]
> Isn't this intentional? We call calculate when something changes like a connection added or deleted, so we want to discard any calculations based on the old info.

May be its intentional to discard old calculation. But `calculate()` only `calculateBroadcast` for `ourself` and discards any calculated broadcasts for other peers. Should it perform  `calculateBroadcast` for rest of the peers as well?

**Comment by murali-reddy** [comment]
Never mind. any subsequent calls `lookupOrCalculate` start building up the cache.

> Most of those changes are uninteresting for most broadcast routes, but figuring out which are interesting is the hard part.

Right. I think routes cache should be reset if there is change in the topology as seen by `outself`

**Comment by murali-reddy** [comment]
> We call calculate when something changes like a connection added or deleted, so we want to discard any calculations based on the old info

while this is valid still high number (at the order 200-300 calls per second on 150 node cluster) of calculateBroadcast() resulting from **miss** in `routes.lookupOrCalculate()` is still a concern will open a seperate bug for it. Closing this issue,
