### ISSUE TITLE
Weave mesh comments

### ISSUE THREAD

**Issue by faddat** [weaveworks/mesh#45]
1) talk to @miolini -- I think that he and the weave team in general would have a fascinating conversation.  

2) So right now mesh requires the knowledge of a single node-- why not bootstrap this from bittorrent DHT while using a PSK or certificate to ensure that no neer-do-well's show up and crash your party?  Would require knowledge of zero nodes, and enable glorious networked chaos.  

3) What happens @ >100 nodes?

:).  

BTW, here's an issue list mostly made by @miolini:

https://github.com/meshbird/meshbird/issues/created_by/miolini

Yeah, he's that awesome.

**Comment by peterbourgon** [comment]
> So right now mesh requires the knowledge of a single node-- why not bootstrap this from bittorrent DHT 

Why not? Because knowledge of a single peer is much easier in many respects :) But this is an interesting approach. How would it fare in restricted networks? Knowledge of a single peer is nice in that it's easy to explain and orchestrate in the face of firewalls, VPCs with SGs, etc.

**Comment by peterbourgon** [comment]
Given these are more questions than requests or bugs, I'll close the issue for now. Please feel free to follow up in Slack!
