### ISSUE TITLE
Panic on creating duplicate Gossip?

### ISSUE THREAD

**Issue by jml** [weaveworks/mesh#69]
Why does `NewGossip` panic if a `Gossip` with that id already exists? Why not either return an `error` or return the existing `Gossip`?

See https://github.com/weaveworks/mesh/blob/2534f734d9a18501c3b155cd24877fca0696fb18/router.go#L136

The existing interface makes it difficult to build programs that build `Gossip`s in response to runtime events.

**Comment by bboreham** [comment]
Wasn't needed in the context where this library was originally developed.  Feel free to improve.

**Comment by jml** [comment]
Are there any backwards compatibility constraints I should be aware of?

**Comment by bboreham** [comment]
If you go with "return the existing `Gossip`" then anyone who genuinely made a mistake in passing the same name will be penalised with a strange and subtle bug.  
If you go with "return an `error`" then you break compilation, but the fix is obvious.

I guess there are other ways to skin the cat.

**Comment by jml** [comment]
Gotcha. Main thing is I want to check whether we've made binding promises such that we won't change the public API.
