### ISSUE TITLE
How to change peers?

### ISSUE THREAD

**Issue by jml** [weaveworks/mesh#72]
For alertmanager, we'd like to be able to update the set of peers in a gossip, based on discovered kubernetes pods. What's the right way to do this?

Currently, I'm doing something like

```go
meshRouter.ConnectionMaker.InitiateConnections(peers, true)
```

where `meshRouter` is a `mesh.Router`

Sub-questions:

* does this remove / disconnect old peers?
* does it add new ones?
* what happens to peers that remain present across updates?
* if `peers` includes the current node, what happens?

**Comment by rade** [comment]
> ```go
> meshRouter.ConnectionMaker.InitiateConnections(peers, true)
> ```

That is effectively what [`weave connect --replace`](https://www.weave.works/docs/net/latest/using-weave/finding-adding-hosts-dynamically/) invokes in Weave Net, so seems like a sensible choice. cc @bboreham

> does this remove / disconnect old peers?

remove yes, disconnect no.  It will prevent reconnection attempts once connections to old peers have been dropped.

> does it add new ones?

yes

> what happens to peers that remain present across updates?

Any existing connections are retained.

> if `peers` includes the current node, what happens?

One connection attempt is made, and an error is logged. No further connection attempts are made to that address.

**Comment by jml** [comment]
Thanks!
